spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: najcOsqIIwCXjOZhAWLqdLyypRsVLvVT
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update